### PR TITLE
Added Makefile

### PR DESCRIPTION
**Pull request by JavaCafe01**
I went ahead and added a Makefile and edited the instructions on the readme. Please make sure to test this yourself.

### CODE REVIEW

**Review by TorchedSammy — CHANGES_REQUESTED** [review]

**Comment by JavaCafe01** [comment]
@TorchedSammy I need more info... 

Can you show me what's in the current directory?

Also, make sure your in the project directory and maybe try a different shell. (Also this seems to be just a go error)

**Comment by TorchedSammy** [comment]
I was in Hilbish's root directory, a normal `go build` worked
I'll try with a different shell when I get home

**Comment by TorchedSammy** [comment]
Same error in zsh

**Comment by JavaCafe01** [comment]
Yes make install needs sudo as it copies and installs files to something under /user. It won't work without it. Make build will work without sudo.

**Comment by TorchedSammy** [comment]
Error was on my part, tested with `PREFIX=.` and it works as expected, merging

**Review by TorchedSammy — APPROVED** [review]

**Pull request merged**
